In [14]:
from __future__ import print_function
import torch

# 행렬 선언
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [15]:
x = torch.rand(5,3) # 무작위 초기화 행렬
print(x)

tensor([[0.1460, 0.3969, 0.5473],
        [0.7534, 0.8186, 0.1324],
        [0.7662, 0.1607, 0.9954],
        [0.8065, 0.9864, 0.2500],
        [0.7157, 0.9399, 0.3953]])


In [16]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [17]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [18]:
x = x.new_ones(5,3, dtype=torch.double) #new_*는 크기를 받음
print(x)

x = torch.randn_like(x, dtype=torch.float) #dtype을 오버라이드
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6162, -0.8739,  0.1833],
        [ 1.6186, -0.0724, -1.9492],
        [ 0.4004,  0.2716,  0.2368],
        [ 1.2373,  1.6041,  0.7945],
        [ 0.3909,  0.0030, -0.4504]])


In [19]:
print(x.size())

torch.Size([5, 3])


In [20]:
y = torch.rand(5,3)

print(x+y)

tensor([[ 1.3588, -0.5348,  0.8126],
        [ 2.2588, -0.0261, -1.8966],
        [ 0.4691,  0.9672,  0.2469],
        [ 1.5759,  1.8600,  1.0844],
        [ 0.9594,  0.8429,  0.2081]])


In [21]:
print(torch.add(x,y))

tensor([[ 1.3588, -0.5348,  0.8126],
        [ 2.2588, -0.0261, -1.8966],
        [ 0.4691,  0.9672,  0.2469],
        [ 1.5759,  1.8600,  1.0844],
        [ 0.9594,  0.8429,  0.2081]])


In [25]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

y.add_(x) # add뒤에 _ 가 붙음
print(y)

tensor([[ 1.3588, -0.5348,  0.8126],
        [ 2.2588, -0.0261, -1.8966],
        [ 0.4691,  0.9672,  0.2469],
        [ 1.5759,  1.8600,  1.0844],
        [ 0.9594,  0.8429,  0.2081]])
tensor([[ 1.3588, -0.5348,  0.8126],
        [ 2.2588, -0.0261, -1.8966],
        [ 0.4691,  0.9672,  0.2469],
        [ 1.5759,  1.8600,  1.0844],
        [ 0.9594,  0.8429,  0.2081]])


In [26]:
print(x[:,1])

tensor([-0.8739, -0.0724,  0.2716,  1.6041,  0.0030])


In [27]:
print(x[0,:])

tensor([ 0.6162, -0.8739,  0.1833])


In [28]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1은 다른 차원에서 유추 (x가 4*4이기 때문에 뒤에가 8이면 앞에가 2가됨)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
x = torch.randn(1)
print(x)
print(x.item()) #tensor에 하나의 값만 존재한다면 item을 사용하면 숫자값을 얻을수 있음

tensor([1.5329])
1.5328867435455322


In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [33]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [34]:
# numpy 배열을 torch tensor로 변환하기
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
